version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app/
      - /app/node_modules
  api:
    build:
      context: ./api
    ports:
      - "5000:5001"
      - "9229:9229"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - /app/node_modules
  db:
    build:
      context: ./db
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-volume:
# version: "3"
# services:
#   db:
#     image: postgres:13.8-alpine3.16
#     restart: always
#     volumes:
#       - db-volume:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=password
#   api:
#     build:
#       context: ./api
#     ports:
#       - "5000:5001"
#     environment:
#       - API_PORT=5001
#       - DATABASE_URL=postgres://postgres:password@db:5432/postgres
#     command: npm run start
#     depends_on:
#       - db
#   client:
#     build:
#       context: ./client
#     ports:
#       - "3000:3000"
#     environment:
#       - REACT_APP_API_URL=http://localhost:5001
#     depends_on:
#       - api
# volumes:
#   db-volume:
